# Práctica II 
## Nombre: Ignacio Yuste López

1. El algoritmo de Luhn es una suma de verificación para validar números de tarjetas y cuentas bancarias.  Implementa la función `is_luhn_valid(cc)`que devuelva una variable booleana que toma el valor `True` si la hilera `cc` es válida y `False`en caso contrario. La hilera de caracteres, que contendrá números, puede tener espacios entre ellos. Por ejemplo, '4799 2739 8713 6272'.

In [7]:
def is_luhn_valid(hilera):
    hilera_mod = list(hilera.replace(" ",""))
    hilera_mod = hilera_mod[::-1]
    sum_total = 0
    
    for i in range(0,len(hilera_mod)):
        
        #Multiplico por 2 los elementos en índices pares
        if(i%2==1):
            hilera_mod[i]=2*int(hilera_mod[i])
        
        #Separo los dígitos de los números y los sumo
        dig1 = int(hilera_mod[i])//10
        dig2 = int(hilera_mod[i])%10
        hilera_mod[i] = dig1+dig2
        
        #Sumo todos los elementos
        sum_total+=hilera_mod[i]
        
    return sum_total%10==0
    

numero =  '1234 5678 12345670'
numero2 = '1234 5678 12345678'
print("Numero 1: 1234567812345670 ->",format(is_luhn_valid(numero)))
print("Numero 2: 1234567812345678 ->",format(is_luhn_valid(numero2)))
            

Numero 1: 1234567812345670-> True
Numero 2: 1234567812345678-> False


In [ ]:
#Método is_luhn_valid sacado de Wikipedia

def is_luhn_valid(cc):

    num = map(int, str(cc))
    return sum(num[::-2] + [sum(divmod(d * 2, 10)) for d in num[-2::-2]]) % 10 == 0

2. Explica el funcionamiento del algoritmo de Luhn explicando el resultado sobre varios ejemplos.

El algoritmo tiene 4 pasos:
    1. Se invierte la secuencia
    2. Se multiplica cada dígito par (impar según la indexación de 
    python) por 2.
    3. Se suman el resto de dígitos con los obtenidos en el paso 
    anterior.
    4. Se calcula el módulo 10
Si el resultado es 0 entonces la secuencia de dígitos es correcta

Por ejemplo, para la secuencia 1234567812345670 tras el algoritmo la suma es 60 por lo que es correcto. Para 1234567812345678 la suma es 68, por lo que no es válido.

3. Modifica la clase base `BankAccount`para verificar que el número de cuenta que se pasa a `__init__()` el test de Luhn. Escribe la nueva definición de la clase `BankAccount`a continuación.

In [26]:
class BankAccount:
    """ A abstract base class representing a bank account."""
    currency = '$'
    
    def __init__(self, customer, account_number, balance=0):
        """
        Initialize the BankAccount class with a customer, account number 
        and opening balance (which defaults to 0.)
        """
        
        
        self.customer = customer
        
        if self.is_luhn_valid(account_number): self.account_number = account_number
        else: print("Numero de cuenta no valido")
        
        self.balance = balance
    
    def is_luhn_valid(hilera):
        hilera_mod = list(hilera.replace(" ",""))
        hilera_mod = hilera_mod[::-1]
        sum_total = 0

        for i in range(0,len(hilera_mod)):

            #Multiplico por 2 los elementos en índices pares
            if(i%2==1):
                hilera_mod[i]=2*int(hilera_mod[i])

            #Separo los dígitos de los números y los sumo
            dig1 = int(hilera_mod[i])//10
            dig2 = int(hilera_mod[i])%10
            hilera_mod[i] = dig1+dig2

            #Sumo todos los elementos
            sum_total+=hilera_mod[i]


        return sum_total%10==0
    
    def deposit(self, amount):
        """ Deposit amount into the bank account."""
        if amount > 0:
            self.balance += amount
        else:
            print('Invalid deposit amount:', amount)
            
    def withdraw(self, amount):
        """
        Withdraw amount from the bank account, ensuring there are sufficient
        funds.
        """
        
        if amount > 0:
            if amount > self.balance:
                print('Insufficient funds')
            else:
                self.balance -= amount
        else:
            print('Invalid withdrawal amount:', amount)

4. Modifica la clase `Current_Account`para que permita números rojos. El límite en rojo de una cuenta debería ser definido en el constructor `__init__()`permitiendo retirar dinero hasta ese límite. Escribe la nueva definición de la clase BankAccounta continuación.

In [27]:
 class CurrentAccount(BankAccount):
    """ A class representing a current (checking) account. """
    def __init__(self, customer, account_number, annual_fee,transaction_limit, balance=0):
        """ Initialize the current account. """
        self.annual_fee = annual_fee
        self.transaction_limit = transaction_limit
        self.red_limit = 100
        super().__init__(customer, account_number, balance)
        
    def withdraw(self, amount):
        """
        Withdraw amount if sufficient funds exist in the account and amount
        is less than the single transaction limit.
        """
        
        if amount <= 0:
            print('Invalid withdrawal amount:', amount)
            return
        
        if amount > self.balance:
            if amount > self.balance + self.red_limit:
                print('Insufficient funds')
                return
            else:
                print('Account in debt')

        
        if amount > self.transaction_limit:
            print('{0:s}{1:.2f} exceeds the single transaction limit of {0:s}{2:.2f}'
                  .format(self.currency, amount,self.transaction_limit))
            return
        
        self.balance -= amount
    
    def apply_annual_fee(self):
        """ Deduct the annual fee from the account balance. """
        self.balance = max(0., self.balance - self.annual_fee)

5. Define dos funciones `add_row()` y `add_column()` que admitan como entrada un array de NumPy y devuelvan una nueva matriz con una fila o una columna más de unos, respectivamente. Comprueba su funcionamiento con

In [33]:
def add_row(matrix):
    return np.stack([matrix, np.array([1 for x in range(matrix.shape[0])])])

def add_column(matrix):
    return np.hstack([matrix,np.reshape(np.array([1 for i in range(matrix.shape[0])]),(2,1))])

In [34]:
import numpy as np
a=np.array([1,2,3,4])
b=np.linspace(0,5,6).reshape(2,3)
print("antes")
print(a)
print(b)

print("despues")
print(add_row(a))
print(add_column(b))

antes
[1 2 3 4]
[[0. 1. 2.]
 [3. 4. 5.]]
despues
[[1 2 3 4]
 [1 1 1 1]]
[[0. 1. 2. 1.]
 [3. 4. 5. 1.]]


6. Escribe una línea de código de Python que devuelva `True`si un array de NumPy es una secuencia de números es estrictamente creciente y `False` en caso contrario. Los métodos de NumPy `np.diif()`y `np.all()` te pueden ayudar.

Comprueba su funcionamiento con 

In [57]:
def growing_array(a): 
    return np.all(np.diff(a)>0)

In [58]:
a=np.array([1,2,3,4])
b=np.array((1,1,2,3,4))
c=np.array((0,1,2,3,4,3,5))

print(a)
print(b)
print(c)
print(growing_array(a))
print(growing_array(b))
print(growing_array(c))

[1 2 3 4]
[1 1 2 3 4]
[0 1 2 3 4 3 5]
True
False
False


7. Explica la siguiente conducta de Python

In [109]:
 x = np.uint8(250)
print(x*2)


x = np.array([250,], dtype=np.uint8)
print((x*2)[0])

500
244


Esto se debe a que en el primer _print_  el resultado de la multiplicación no se almacena en una variable tipo _uint8_, simplemente se calcula y se envía al cauce de salida. En cambio, en el segundo _print_ estamos forzando a que se almacene el resultado de la operación en un elemento de un array de tipo _uint8_ y este solo puede almacenar valores hasta 255, por lo que en cuanto la secuencia de bytes sobrepasa la capacidad la trunca, es por eso que el valor obtenido es 24

8. Escribe código en Python para crear un array de NumPy 10x10 con los elementos de las fronteras cero y el interior 1.

In [13]:
lado_matriz = 10
my_array = np.zeros([lado_matriz,lado_matriz])
my_array[1:-1,1:-1]=1
print(my_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


9. Escribe un programa en Python que permute dos filas de una matriz. Prueba, por ejemplo, con las dos primeras filas de 

In [39]:
def permuta_filas(matrix,i,j):
    fila1 = np.copy(matrix[i])
    matrix[i] = matrix[j]
    matrix[j] = fila1
    return matrix

In [40]:
my_array = np.arange(12).reshape(3, 4)
print(my_array)
my_array = permuta_filas(my_array,0,1)
print(my_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


10. Haz lo mismo con las columnas

In [42]:
def permuta_columnas(matrix,i,j):
    col1 = np.copy(matrix[:,i])
    matrix[:,i] = matrix[:,j]
    matrix[:,j] = col1
    return matrix

In [43]:
my_array = np.arange(12).reshape(3, 4)
print(my_array)
my_array = permuta_columnas(my_array,0,1)
print(my_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]
